tinoshop_demo2/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using tinoshop_demo2.Data;
using tinoshop_demo2.Models;

namespace tinoshop_demo2.Controllers
{
    public class ShopController : Controller
    {
		private readonly tinoshop_demo2Context _context;

		public ShopController(tinoshop_demo2Context context)
		{
			_context = context;
		}

		public async Task<IActionResult> Index()
        {
			var tinoshop = _context.Product.Include(s => s.Category);
			return View(await tinoshop.ToListAsync());
		}

   //     public async Task<IActionResult> Index(int? pageNumber = 1)
   //     {
			//var sanphams = from s in _context.Product select s;
			//int pageSize =6;
			//pageNumber = pageNumber< 1 ? 1 : pageNumber;
			//sanphams = _context.Product.Include(s => s.Category);
   //         return View(await PageList<Product>.CreateAsync(sanphams.AsNoTracking(), pageNumber ?? 1, pageSize));
   //     }

        public async Task<IActionResult> TheLoai(int? ID)
        {
            var tinoshop = _context.Product.Include(s => s.Category);
            return View("TheLoai", await tinoshop.Where(s => s.CategoryID == ID).ToListAsync());
        }

		[HttpPost]
		public async Task<IActionResult> TimKiem(String timKiem)
		{
			var tinoshop = _context.Product.Include(s => s.ProductName);
			return View("TheLoai", await _context.Product.Where(s => s.ProductName!.Contains(timKiem)).ToListAsync());
		}
	}
}

tinoshop_demo2/Controllers/_CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using tinoshop_demo2.Data;

namespace tinoshop_demo2.Controllers
{
	[ViewComponent(Name ="_Category")]

	public class _CategoryViewComponent : ViewComponent
	{
		private readonly tinoshop_demo2Context _context;

		public _CategoryViewComponent(tinoshop_demo2Context context)
		{
			_context = context;
		}
		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View("_Category", await _context.Category.ToListAsync());
		}
	}
}

tinoshop_demo2/Views/Shop/Index.cshtml
@model IEnumerable<tinoshop_demo2.Models.Product>

@*@model PageList<tinoshop_demo2.Models.Product>*@

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

	<div class="hero-wrap hero-bread" style="background-image: url('/images/bg_6.jpg');">
		<div class="container">
			<div class="row no-gutters slider-text align-items-center justify-content-center">
				<div class="col-md-9 ftco-animate text-center">
				<p class="breadcrumbs"><span class="mr-2"><a href="/Home">Home</a></span> <span class="mr-2"><a href="/Shop">Shop</a></span></p>
					<h1 class="mb-0 bread">Shop</h1>
					<form asp-controller="Shop" asp-action="TimKiem">
						<input type="text" name="timKiem" />
						<input type="submit" name="timKiem" value="Tìm kiếm" class="btn btn-info" />
					</form>
				</div>
			</div>
		</div>
	</div>

	<section class="ftco-section bg-light">
		<div class="container">
			<div class="row">
				<!--nhet san pham vao day-->
			<div class="col-md-8 col-lg-10 order-md-last">
				<div class="row">
					@foreach(var item in Model)
					{
						<div class="col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex">
						<div class="product d-flex flex-column">
							<a href="/Products/Details/@item.ProductID" class="img-prod">
								<img class="img-fluid" src="@item.ProductImage" alt="Colorlib Template">
								<div class="overlay"></div>
							</a>
							<div class="text py-3 pb-4 px-3">
								<div class="d-flex">
									<div class="cat">
										<span>@item.Category.CategoryName</span>
										@*<p>TiNo Shop</p>*@
									</div>
									<div class="rating">
										<p class="text-right mb-0">
											<a href="#"><span class="ion-ios-star-outline"></span></a>
											<a href="#"><span class="ion-ios-star-outline"></span></a>
											<a href="#"><span class="ion-ios-star-outline"></span></a>
											<a href="#"><span class="ion-ios-star-outline"></span></a>
											<a href="#"><span class="ion-ios-star-outline"></span></a>
										</p>
									</div>
								</div>
								<h3><a href="#">@item.ProductName</a></h3>
								<div class="pricing">
									<p class="price"><span>@item.ProductPrice</span>đ</p>
								</div>
								<p class="bottom-area d-flex px-3">
									<a href="#" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a>
									<a href="#" class="buy-now text-center py-2">Buy now<span><i class="ion-ios-cart ml-1"></i></span></a>
								</p>
							</div>
						</div>
					</div>
					}
				</div>
				@*<div class="flex-c-m flex-w w-full p-t-45">
					@{
						var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
						var nextDisabled = !Model.HasNextPage ? "disabled" : "";
					}

					<a asp-action="Index"
					   asp-route-sortOrder="@ViewData["CurrentSort"]"
					   asp-route-pageNumber="@(Model.PageIndex - 1)"
					   asp-route-currentFilter="@ViewData["CurrentFilter"]" class="btn btn-default @prevDisabled">
						Previous
					</a>
					<a asp-action="Index"
					   asp-route-sortOrder="@ViewData["CurrentSort"]"
					   asp-route-pageNumber="@(Model.PageIndex + 1)"
					   asp-route-currentFilter="@ViewData["CurrentFilter"]" class="btn btn-default @nextDisabled">
						Next
					</a>
				</div>*@
				@*<div class="row mt-5">
				<div class="col text-center">
				<div class="block-27">
				<ul>
				<li><a href="#">&lt;</a></li>
				<li class="active"><span>1</span></li>
				<li><a href="#">2</a></li>
				<li><a href="#">3</a></li>
				<li><a href="#">4</a></li>
				<li><a href="#">5</a></li>
				<li><a href="#">&gt;</a></li>
				</ul>
				</div>
				</div>
				</div>*@
			</div>
				@(await Component.InvokeAsync("_Category"))
				<!--nhet category vao day-->
			</div>
		</div>
	</section>

	<section class="ftco-gallery">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-8 heading-section text-center mb-4 ftco-animate">
					<h2 class="mb-4">Follow Us On Instagram</h2>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
				</div>
			</div>
		</div>
		<div class="container-fluid px-0">
			<div class="row no-gutters">
				<div class="col-md-4 col-lg-2 ftco-animate">
					<a href="~/images/gallery-1.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-1.jpg);">
						<div class="icon mb-4 d-flex align-items-center justify-content-center">
							<span class="icon-instagram"></span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-2.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-2.jpg);">
						<div class="icon mb-4 d-flex align-items-center justify-content-center">
							<span class="icon-instagram"></span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-3.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-3.jpg);">
						<div class="icon mb-4 d-flex align-items-center justify-content-center">
							<span class="icon-instagram"></span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-4.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-4.jpg);">
						<div class="icon mb-4 d-flex align-items-center justify-content-center">
							<span class="icon-instagram"></span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-5.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-5.jpg);">
						<div class="icon mb-4 d-flex align-items-center justify-content-center">
							<span class="icon-instagram"></span>
						</div>
					</a>
				</div>
				<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-6.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-6.jpg);">
						<div class="icon mb-4 d-flex align-items-center justify-content-center">
							<span class="icon-instagram"></span>
						</div>
					</a>
				</div>
			</div>
		</div>
	</section>

tinoshop_demo2/Views/Shop/TheLoai.cshtml
@model IEnumerable<tinoshop_demo2.Models.Product>

@*@model PageList<tinoshop_demo2.Models.Product>*@

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="hero-wrap hero-bread" style="background-image: url('/images/bg_6.jpg');">
	<div class="container">
		<div class="row no-gutters slider-text align-items-center justify-content-center">
			<div class="col-md-9 ftco-animate text-center">
				<p class="breadcrumbs"><span class="mr-2"><a href="/Home">Home</a></span> <span>Shop</span></p>
				<h1 class="mb-0 bread">Shop</h1>
				<form asp-controller="Shop" asp-action="TimKiem">
					<input type="text" name="timKiem" />
					<input type="submit" name="timKiem" value="Tìm kiếm" class="btn btn-info" />
				</form>
			</div>
		</div>
	</div>
</div>

<section class="ftco-section bg-light">
	<div class="container">
		<div class="row">
			<!--nhet san pham vao day-->
			<div class="col-md-8 col-lg-10 order-md-last">
				<div class="row">
					@foreach (var item in Model)
					{
						<div class="col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex">
							<div class="product d-flex flex-column">
								<a href="/Products/Details" class="img-prod">
									<img class="img-fluid" src="@item.ProductImage" alt="Colorlib Template">
									<div class="overlay"></div>
								</a>
								<div class="text py-3 pb-4 px-3">
									<div class="d-flex">
										<div class="cat">
											@*<span>@item.Category.CategoryName</span>*@
											<p>TiNo Shop</p>
										</div>
										<div class="rating">
											<p class="text-right mb-0">
												<a href="#"><span class="ion-ios-star-outline"></span></a>
												<a href="#"><span class="ion-ios-star-outline"></span></a>
												<a href="#"><span class="ion-ios-star-outline"></span></a>
												<a href="#"><span class="ion-ios-star-outline"></span></a>
												<a href="#"><span class="ion-ios-star-outline"></span></a>
											</p>
										</div>
									</div>
									<h3><a href="#">@item.ProductName</a></h3>
									<div class="pricing">
										<p class="price"><span>@item.ProductPrice</span>đ</p>
									</div>
									<p class="bottom-area d-flex px-3">
										<a href="#" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a>
										<a href="#" class="buy-now text-center py-2">Buy now<span><i class="ion-ios-cart ml-1"></i></span></a>
									</p>
								</div>
							</div>
						</div>
					}
				</div>
				@*<div class="flex-c-m flex-w w-full p-t-45">
				@{
				var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
				var nextDisabled = !Model.HasNextPage ? "disabled" : "";
				}

				<a asp-action="Index"
				asp-route-sortOrder="@ViewData["CurrentSort"]"
				asp-route-pageNumber="@(Model.PageIndex - 1)"
				asp-route-currentFilter="@ViewData["CurrentFilter"]" class="btn btn-default @prevDisabled">
				Previous
				</a>
				<a asp-action="Index"
				asp-route-sortOrder="@ViewData["CurrentSort"]"
				asp-route-pageNumber="@(Model.PageIndex + 1)"
				asp-route-currentFilter="@ViewData["CurrentFilter"]" class="btn btn-default @nextDisabled">
				Next
				</a>
				</div>*@
				@*<div class="row mt-5">
				<div class="col text-center">
				<div class="block-27">
				<ul>
				<li><a href="#">&lt;</a></li>
				<li class="active"><span>1</span></li>
				<li><a href="#">2</a></li>
				<li><a href="#">3</a></li>
				<li><a href="#">4</a></li>
				<li><a href="#">5</a></li>
				<li><a href="#">&gt;</a></li>
				</ul>
				</div>
				</div>
				</div>*@
			</div>
			@(await Component.InvokeAsync("_Category"))
			<!--nhet category vao day-->
		</div>
	</div>
</section>

<section class="ftco-gallery">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8 heading-section text-center mb-4 ftco-animate">
				<h2 class="mb-4">Follow Us On Instagram</h2>
				<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
			</div>
		</div>
	</div>
	<div class="container-fluid px-0">
		<div class="row no-gutters">
			<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-1.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-1.jpg);">
					<div class="icon mb-4 d-flex align-items-center justify-content-center">
						<span class="icon-instagram"></span>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-2.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-2.jpg);">
					<div class="icon mb-4 d-flex align-items-center justify-content-center">
						<span class="icon-instagram"></span>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-3.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-3.jpg);">
					<div class="icon mb-4 d-flex align-items-center justify-content-center">
						<span class="icon-instagram"></span>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-4.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-4.jpg);">
					<div class="icon mb-4 d-flex align-items-center justify-content-center">
						<span class="icon-instagram"></span>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-5.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-5.jpg);">
					<div class="icon mb-4 d-flex align-items-center justify-content-center">
						<span class="icon-instagram"></span>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-lg-2 ftco-animate">
				<a href="~/images/gallery-6.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(images/gallery-6.jpg);">
					<div class="icon mb-4 d-flex align-items-center justify-content-center">
						<span class="icon-instagram"></span>
					</div>
				</a>
			</div>
		</div>
	</div>
</section>